#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("EventDemo.Resource", IsApplication=true)]

namespace EventDemo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int gradient_bg = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int gradient_bg_hover = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_launcher = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_tab_my_schedule = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_tab_my_schedule_selected = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_tab_my_schedule_unselected = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_tab_sessions = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_tab_sessions_selected = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_tab_sessions_unselected = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_tab_speakers = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_tab_speakers_selected = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_tab_speakers_unselected = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_tab_whats_on = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_tab_whats_on_selected = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_tab_whats_on_unselected = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Icon = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int index1 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int index2 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int index3 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int index4 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int index5 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int index6 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int index7 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int index8 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int list_selector = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int splash = 2130837529;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060003
			public const int Heading = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int Image = 2131099648;
			
			// aapt resource value: 0x7f060007
			public const int List = 2131099655;
			
			// aapt resource value: 0x7f060004
			public const int SampleVideoView = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int SubHeading = 2131099654;
			
			// aapt resource value: 0x7f060001
			public const int Text1 = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int Text2 = 2131099650;
			
			// aapt resource value: 0x7f060008
			public const int gallery1 = 2131099656;
			
			// aapt resource value: 0x7f060005
			public const int linearLayout1 = 2131099653;
			
			// aapt resource value: 0x7f060009
			public const int mediaController1 = 2131099657;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CustomTableView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DetailView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int SimpleView = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
